services:
  database: 
    image: postgres:17.6
    container_name: postgres-db-mercadito
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${PGPORT}:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    container_name: redis-mercadito
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis:/data
    